lib/rspec_api_documentation/views/markup_example.rb, lib/rspec_api_documentation/writers/combined_text_writer.rb, lib/rspec_api_documentation/writers/json_writer.rb
Allow resource name be a Class, e.g.:
```ruby
resource Postcode do
end
```
Prevents `undefined method 'downcase' for #<Class`
=> Allow resource name be a Class

lib/rspec_api_documentation/writers/json_writer.rb, spec/writers/json_example_spec.rb
* When user names a resource with a leading slash, library was trying to create
a directory at the root directory of the machine
* Failure was at `lib/rspec_api_documentation/writers/json_writer.rb:18` (which
is where dir is being made based on resource name)
* This resulted in permissions errors that were hard to debug
* This change strips leading slash when evaluating which dir to put docs into
=> Remove leading slashes from dirname

lib/rspec_api_documentation/headers.rb, spec/http_test_client_spec.rb
I had problems with headers, ending with "id". Function titleize cuts "id".
=> headers ending in "id" are displayed correctly

Gemfile.lock, Rakefile, rspec_api_documentation.gemspec
`rake release` helps create tag and push gem to rubygems.
=> Add bundler gem tasks

lib/rspec_api_documentation/writers/json_writer.rb
- store route and http method in JsonIndex to show on index page
- this can make understanding the API request simpler
- no need to check detailed info of API request
- closes #209
=> added 'route' url and http 'method' for all JsonIndex examples

lib/rspec_api_documentation/dsl/endpoint.rb, spec/dsl_spec.rb
=> Ability to set nested scopes

README.md, lib/rspec_api_documentation/dsl/endpoint.rb, spec/dsl_spec.rb
There is a small bug when a parameter is in the path and under some scopes.
```
PUT /articles/:id
{
"data": {
"type": "articles",
"id": "1",
"attributes": {
"title": "To TDD or Not"
}
}
}
```
It wasn't possible to set the internal `id` because it was checked the presence in the path.
I've changed to check in the path the presence of the full name (with the scope), since the id in the path won't have any scope the following will work:
```
parameter :id, 'path id', required: true
parameter :id, 'data id', scope: :data, required: true
let(:id) { 1 }
let(:data_id) { 1 }
```
I've also improved a bit the readme about scopes
=> Add the ability to set the value of nested params

lib/rspec_api_documentation/dsl/resource.rb, spec/dsl_spec.rb
* if description is not specified
=> infer parameter description from name and scope

lib/rspec_api_documentation.rb
This fixes a problem in a project I am working on. We are working on a non-rails project but pull in some rails libraries for html sanitization. These libraries define Rails but not Rails::Railtie, thus rspec_api_documentation blows up when it tries to load the railtie.
=> Only load the railtie if Rails::Railtie is defined

lib/rspec_api_documentation/headers.rb, spec/headers_spec.rb
The Content-Type header was getting mangled to "Content_type". Which caused masking of multipart-data to break.
Fixes #239
=> Fix Content-Type Header

README.md, lib/rspec_api_documentation/client_base.rb, lib/rspec_api_documentation/configuration.rb, spec/http_test_client_spec.rb
Supports
- application/json
- application/vnd.api+json
- application/vnd.api+json; supported-ext="bulk,jsonpatch"
the JSON API spec uses `application/vnd.api+json`
http://jsonapi.org/extensions/#extension-negotiation
=> JSON Content-Type matcher is more inclusive

README.md, lib/rspec_api_documentation/configuration.rb, lib/rspec_api_documentation/dsl/endpoint.rb, spec/configuration_spec.rb, spec/dsl_spec.rb
Allow legacy configuration `post_body_formatter`
in response to issue https://github.com/zipmark/rspec_api_documentation/issues/243
=> rename config post_body_formatter to be request_body_formatter

lib/tasks/docs.rake
As I didn't know for sure what exact version the change happened (major > 2?),
I checked inside RSpec::Core::Ordering::Registry.
If we're comfortable with making the switch on version 2 to 3 of RSpec, I can
change the condition to check `Gem.latest_spec_for('rspec-core').version.segments[0]`.
This should fix #192.
=> Pass rspec the right --order option (`default` or `defined`).

lib/rspec_api_documentation/dsl.rb, spec/dsl_spec.rb
If using a class as the resource:
```ruby
resource Order do
end
```
The `resource_name` will be a class, which causes issues when sorting for
sections. By calling `#to_s` on the `args.first` when first dealing with
the resource we can ensure that we are always working with a string for
the `resource_name`.
-----
Also refactored to use a ternary operator instead of a one-line `if else end`.
=> Allow Class Resources, call `#to_s` for defined resource_name

lib/rspec_api_documentation/dsl.rb
Previous, we just check that `RSpec::Rails` was defined, which it can be yet *not* have `RSpec::Rails::DIRECTORY_MAPPINGS` defined. Lets ensure it is defined.
=> Ensure that DIRECTORY_MAPPINGS is available

Gemfile.lock, rspec_api_documentation.gemspec
Since JSON is packaged with Ruby 1.9.3, we don't need to add it as a runtime dependency.
=> remove json as a runtime dependency

features/slate_documentation.feature, lib/rspec_api_documentation.rb, lib/rspec_api_documentation/views/slate_example.rb, lib/rspec_api_documentation/writers/slate_writer.rb, spec/views/slate_example_spec.rb, spec/writers/slate_writer_spec.rb, templates/rspec_api_documentation/slate_example.mustache
See #275. This pull request defines `SlateWriter` to make it easy to generate docs that [Slate](https://github.com/tripit/slate) can process. It writes all examples to one Slate partial (for ease of including in Slate output along with other doc files), and the output template is optimized to work well with Slate's default stylesheets.
=> Add a writer for Slate

.gitignore, README.md, features/combined_json.feature, features/combined_text.feature, features/curl.feature, features/headers.feature, features/html_documentation.feature, features/json_iodocs.feature, features/markdown_documentation.feature, features/oauth2_mac_client.feature, features/patch.feature, features/readme.md, features/redefining_client.feature, features/textile_documentation.feature, features/upload_file.feature, lib/rspec_api_documentation/dsl/resource.rb, lib/rspec_api_documentation/example.rb, lib/rspec_api_documentation/writers/index_helper.rb, lib/rspec_api_documentation/writers/json_writer.rb, spec/dsl_spec.rb, spec/example_spec.rb, spec/writers/index_helper_spec.rb, templates/rspec_api_documentation/html_example.mustache, templates/rspec_api_documentation/html_index.mustache, templates/rspec_api_documentation/markdown_example.mustache, templates/rspec_api_documentation/markdown_index.mustache, templates/rspec_api_documentation/textile_example.mustache, templates/rspec_api_documentation/textile_index.mustache
I just merged the fork of @jramos #196 with the current master. The tests seem to all be fine.
This should cover #186.
=> Another attempt at adding explanations to resources

features/markdown_documentation.feature, lib/rspec_api_documentation/views/markdown_example.rb, templates/rspec_api_documentation/markdown_example.mustache
The parameters in the previous markdown view were pretty ugly, and did not show the `scope` parameters. I made is so parameters are now rendered in a markdown table instead.
I ran into one hitch, I could not for the life of me make the cucumber spec pass. I manually ran:
`be rspec app_spec.rb --require ./app.rb --format RspecApiDocumentation::ApiFormatter`
Against a copy and pasted `app_spec.rb` and `app.rb`, and then diffed the outputs. They were exactly the same. I have no idea how to debug these cucumber tests, so I am probably doing it wrong. Any tips would be hugely appreciated :smile: 
Thanks for maintaining such a useful project!
EDIT: Looks like the specs passed on CI! Must be a local bug.
=> Use tables to represent markdown parameters

lib/rspec_api_documentation/curl.rb, lib/rspec_api_documentation/example.rb, spec/example_spec.rb
HTTP headers are case-insensitive, this patch will filter out headers defined on config even if they have different case.
=> Ignore case sensitivity when filtering headers

rspec_api_documentation.gemspec
@erictnguyen I mistakenly merged the 'loosen dependency versioning' PR I had opened up: #298.
Could you please review this reversion PR for the time being? Thanks.
cc @jakehow
This reverts commit f4713c3da52c3f13de2e7f5f64731e314a1da9bb, reversing
changes made to d8570ef76247bdbd73d747511f6c4b102cf82875.
=> Revert "Merge pull request #298 from zipmark/ease-rspec-dep-version"

README.md, lib/rspec_api_documentation/dsl/endpoint.rb, lib/rspec_api_documentation/dsl/endpoint/params.rb, lib/rspec_api_documentation/dsl/endpoint/set_param.rb, spec/dsl_spec.rb
Related to #308 
This PR add a `method` option that allows to use custom methods as a parameter value
For example:
```ruby
post "/orders" do
parameter :name, "Order name", required: true, method: :custom_name
let(:custom_name) { "Custom order name" }
...
end
```
Also made some refactorings
=> Custom parameter method

lib/rspec_api_documentation/views/markup_example.rb, spec/views/html_example_spec.rb
Using special characters in example descriptions may break `git clone` on Windows when API docs are stored in repo. This is mostly because some of these characters are considered as file separators.
I've decided to remove all characters listed here: https://msdn.microsoft.com/en-ca/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions
=> Remove all windows-illegal characters from filenames

lib/rspec_api_documentation/writers/slate_writer.rb
=> Make SlateWriter output cURL cmd in separate tab

features/html_documentation.feature, lib/rspec_api_documentation/views/markup_example.rb
=> Fix formatting of nested response_field scopes

README.md
RSpec 3.5 has been released. The reference to the beta in the README is obsolete.
=> Remove RSpec 3.5 beta mention in README

features/markdown_documentation.feature, templates/rspec_api_documentation/markdown_example.mustache
inspired by https://github.com/zipmark/rspec_api_documentation/pull/265
and fixed a typo.
=> Use tables to represent markdown response fields

lib/rspec_api_documentation/railtie.rb
Before this, we were relying on the Gem's `lib` dir being on the `$LOAD_PATH`, and thus `load` would find the `tasks/doc.rake` file. This can break when a different gem also has a `tasks/docs.rake` file, and it's further up in the load path. Same goes for a Rails app with a `tasks/docs.rake` file existing. This ensures we get OUR `tasks/docs.rake` file.
=> Use direct path to rake file

features/slate_documentation.feature, lib/rspec_api_documentation/curl.rb
Currenly if use with Rails-like collection:
```
GET /endpoint?filter[locations][]=Hamburg
```
it fails with 
```
curl: (3) [globbing] bad range
```
This fix turns off the globbing parser for get requests
=> Turn off URL globbing parser for curl get requests

features/upload_file.feature, lib/rspec_api_documentation/client_base.rb
This adding support to clean uploaded data from arrays that contain hashes with files in multipart/form-data requests.
=> Clean out uploaded data from arrays

features/slate_documentation.feature, templates/rspec_api_documentation/slate_example.mustache
=> Fix Slate template

README.md
Modern version of rails use `rails_helper` instead of `spec_helper` to pull in rails dependencies. With the example as written, the code will not work.
This will fix issues such as https://github.com/zipmark/rspec_api_documentation/issues/258 and http://stackoverflow.com/questions/10536846/why-is-this-rspec-test-throwing-a-undefined-method-call-for-nilnilclass-err
=> Fix require in readme example

README.md, features/api_blueprint_documentation.feature, lib/rspec_api_documentation.rb, lib/rspec_api_documentation/dsl/endpoint.rb, lib/rspec_api_documentation/dsl/resource.rb, lib/rspec_api_documentation/example.rb, lib/rspec_api_documentation/views/api_blueprint_example.rb, lib/rspec_api_documentation/views/api_blueprint_index.rb, lib/rspec_api_documentation/views/markup_example.rb, lib/rspec_api_documentation/writers/api_blueprint_writer.rb, lib/rspec_api_documentation/writers/general_markup_writer.rb, spec/dsl_spec.rb, spec/example_spec.rb, spec/spec_helper.rb, spec/views/api_blueprint_example_spec.rb, spec/views/api_blueprint_index_spec.rb, spec/writers/html_writer_spec.rb, spec/writers/markdown_writer_spec.rb, spec/writers/slate_writer_spec.rb, spec/writers/textile_writer_spec.rb, templates/rspec_api_documentation/api_blueprint_index.mustache
This commit adds API Blueprint (APIB) to this gem. A few highlights:
* APIB groups entities, resources, routes, HTTP verbs and requests
differently than what the gem currently uses. Because of that I had to
override more methods than usual in the `Markup` classes.
APIB has the following structure:
1. resource (e.g "Group Orders")
2. route (e.g "Orders Collection [/orders]")
3. HTTP method (e.g "Loads all orders [GET]")
4. Requests. Here, we show all different requests which means that
we don't have the repetition of GET for each example. All
examples stay under one, unified HTTP method header.
* APIB differentiates parameters (values used in the URLs) from
attributes (values used in the actual request body). You can use
`attributes` in your texts.
* APIB has a `route` header, which means …
=> Adds API Blueprint

README.md, example/spec/acceptance_helper.rb, features/api_blueprint_documentation.feature, features/html_documentation.feature, features/json_iodocs.feature, features/markdown_documentation.feature, features/slate_documentation.feature, features/textile_documentation.feature, lib/rspec_api_documentation/configuration.rb, lib/rspec_api_documentation/views/markup_index.rb, lib/rspec_api_documentation/writers/json_iodocs_writer.rb, spec/configuration_spec.rb, templates/rspec_api_documentation/html_index.mustache, templates/rspec_api_documentation/markdown_index.mustache, templates/rspec_api_documentation/textile_index.mustache
Added `api_explanation` to the config. Naming is opinionated but stays in tact with the one used inside rspec examples.
=> Add common api description before resources sections (closes #354)

lib/rspec_api_documentation/curl.rb
In my current project a request header has an integer value. 
`RspecApiDocumentation::Curl#format_auth_header` tries to send `#gsub` to the value which Numerics do not respond to. I added a naive check for that.
=> Fix integer as header value

lib/rspec_api_documentation/dsl/endpoint/set_param.rb, spec/dsl_spec.rb
The `method` arg of `parameter` macro is used to solve conflicts with existing methods on the spec context. This works well when you define the value for `method` arg.
When the specified method is not defined, the original param name is used.
In the example below, the current behavior raises 'No response yet' because `status` is a reserved method of rack test.
```ruby
get '/foo' do
parameter :status, "Blah", method: :status_param # this param is not required
example 'meh' do
expect(status).to eq 200
end
end
```
The PR removes the fallback that looks for the original param name when the provided `method` is not implemented.
More context here: https://github.com/zipmark/rspec_api_documentation/pull/312#discussion_r126256369
=> Don't evaluate original parameter name when custom method is provided

lib/rspec_api_documentation/configuration.rb
Make sure we recognize `application/vnd.api+json` as JSON to pretty format it
using `response_body_formatter`
=> Recognize JSON API response as JSON

Gemfile.lock, lib/rspec_api_documentation/dsl/endpoint/set_param.rb, spec/dsl_spec.rb
When building out a JSONAPI, every endpoint has a `type` field with a fixed value of the resources name. Writing `parameter :type, 'The object type', value: 'users'` is more clear of it's static nature than looking for a `let`.
More broadly, when using `rspec_api_documentation` for 10-15 projects now. Having `let` reserved for dynamic values and using `value: 3` for things that are static, seems to reduce the "noise" in writing larger spec files.
Not 100% sure on the `value:` naming convention. I also tried having `method` support a block (like  `method: -> { '3' }`), but that did not feel right.
* The specs suite does not seem to like Ruby 2.5.0 with the current `Gemfile.lock`. I suggest removing the `Gemfile.lock` from the repo (`gitignore` it) and depend on the `gemspec`.
* I had to …
=> Parameters accept a value option for fixed values.

features/redefining_same_client.feature, lib/rspec_api_documentation/configuration.rb
=> Fixes undefining client_method when set to the same client_method

lib/rspec_api_documentation/views/markup_example.rb, spec/views/html_example_spec.rb
Using special characters in resource names may break git clone on Windows when API docs are stored in repo. This is mostly because some of these characters are considered as file separators.
The solution is to remove all characters listed here: https://msdn.microsoft.com/en-ca/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions
Note: the same issue was fixed previously, but for `filename` only: https://github.com/zipmark/rspec_api_documentation/pull/300
=> Remove special chars from dirnames

features/api_blueprint_documentation.feature, lib/rspec_api_documentation/dsl/endpoint/params.rb, lib/rspec_api_documentation/views/api_blueprint_example.rb, lib/rspec_api_documentation/views/api_blueprint_index.rb, spec/views/api_blueprint_example_spec.rb, spec/views/api_blueprint_index_spec.rb, templates/rspec_api_documentation/api_blueprint_index.mustache
The API Blueprint generated is wrong and don't work on https://app.apiary.io this PR aim to fix that.
This is the minimum changes to make https://app.apiary.io happy.
This PR is based on the work of 
[Fabien Chaynes](https://github.com/FabienChaynes) @FabienChaynes https://github.com/FinalCAD/rspec_api_documentation/pull/1 and [Steven Vandevelde](https://github.com/icidasset)  @icidasset https://github.com/FinalCAD/rspec_api_documentation/pull/2
They did more, but I think it should be part of another PR.
Please consider those changes.
Thanks
=> Fix API blueprint documentation

lib/rspec_api_documentation.rb, lib/rspec_api_documentation/api_documentation.rb, lib/rspec_api_documentation/writers/combined_json_writer.rb, lib/rspec_api_documentation/writers/json_iodocs_writer.rb, lib/rspec_api_documentation/writers/json_writer.rb, spec/writers/json_example_spec.rb, spec/writers/json_iodocs_writer_spec.rb, spec/writers/json_writer_spec.rb
When running the docs:generate command I was getting the following error:
```
/rspec_api_documentation-5.1.0/lib/rspec_api_documentation/api_documentation.rb:33:in `const_get': uninitialized constant RspecApiDocumentation::Writers::JSONWriter (NameError)
```
Turned out to be this line in `RspecApiDocumentation::ApiDocumentation`:
```
RspecApiDocumentation::Writers.const_get("#{format}_writer".classify)
```
apparently `"json_writer".classify` is now returning `JSONWriter` instead of `JsonWriter`, thus giving the uninitialized constant error
=> Change Json classnames to JSON

features/slate_documentation.feature, lib/rspec_api_documentation/views/slate_index.rb, lib/rspec_api_documentation/writers/slate_writer.rb, spec/writers/slate_writer_spec.rb, templates/rspec_api_documentation/slate_index.mustache
Currently, the Slate formatter (introduced in #282) does not provide a means for common content to be included. This change extracts the YAML front matter and title to its own template. It also adds the API explanation field into the template.
Note that this allows #294 to be resolved because the YAML front matter can be updated in your own custom template.
=> Add index template and api explanation for Slate formatter

features/slate_documentation.feature, lib/rspec_api_documentation/writers/slate_writer.rb
Resource-level [explanations](https://github.com/zipmark/rspec_api_documentation#explanation) were not included in the Slate formatter. This restores resource level explanations under resource sections.
=> Slate resource explanation

features/api_blueprint_documentation.feature, lib/rspec_api_documentation/views/api_blueprint_index.rb, spec/views/api_blueprint_index_spec.rb
API Blueprint renderer will not flag parameters as `optional` if `required: false` is set
By default, API Blueprint [considers all parameters as required](https://apiblueprint.org/documentation/specification.html#def-uriparameters-section#uri-parameters-section). This change adjusts the API Blueprint view object's logic to set "optional" on a parameter if `required: false` is set.  
*note*: if this has the potential to be merged in. I will gladly add test and offer further explanation if needed
=> API Blueprint view object respects required: false for parameters now

Gemfile.lock, README.md, example/Gemfile, example/Gemfile.lock, example/spec/acceptance_helper.rb, rspec_api_documentation.gemspec
This is a pull request that tries to  resolve some of the documentation issues raised issue #386.  The git log explains the changes.
=> Documentation obromios

lib/rspec_api_documentation.rb, lib/rspec_api_documentation/writers/json_writer.rb
=> backward compatibility to use json or JSON in format configuration

lib/rspec_api_documentation/views/api_blueprint_index.rb
While using the API Blueprint formatter, I discovered that this gem will always group your endpoint documentation by route no matter what. This isn't always desirable as some users may want to have a bit more control over how these requests are grouped in documentation.
I attempted to write specs:
```ruby
route '/resource/:id', 'Read Resource' do
get 'fetch resource with specified id' do
#...
end
end
route '/resource/:id', 'Update Resource' do
patch 'update resource with specified id' do
#...
end
end
```
as
```ruby
get '/resource/:id' do
#...
end
post '/resource/:id' do
#...
end
```
But the test suite will fail with `--format RspecApiDocumentation::ApiFormatter` format because no `route_uri` is set.
I would think that these requests would only be grouped together when they are in the same …
=> Fixes API Blueprint route's always grouping

lib/rspec_api_documentation/dsl/endpoint/params.rb
**- What is it good for**
I stumbled over the version 5 to 6 upgrade issue (https://github.com/zipmark/rspec_api_documentation/issues/398) and this is an approach to solve the issue. 
**- What I did**
I debugged the `cur` property to be an array and the `p[:name]` access resulted in an `TypeError: no implicit conversion of String into Integer`. Now we detect this situation and pick the first object of the array. Furthermore we add an additional empty string to the `scopes` array as an indicator. This results in parameter names like this: `props[pictures][][id]`.
**- A picture of a cute animal (not mandatory but encouraged)**
=> Added a fix for the value mapping of an array of objects

README.md, features/open_api.feature, lib/rspec_api_documentation/open_api/parameter.rb, lib/rspec_api_documentation/writers/open_api_writer.rb
**Before this fix**
* the params example are presented in plain text into `description` (#191, #403)
* the rspec_api_documentation duplicates parameters in path (#393, #402)
**After the fix**
* rspec_api_docs now uses [swagger examples](https://swagger.io/docs/specification/2-0/adding-examples/) in open_api;
* rspec_api_docs presents correctly the queries and path parameters.
=> Fix: Issues #191 #402 and #403: Add example property and remove duplicated parameters

features/api_blueprint_documentation.feature, lib/rspec_api_documentation/views/api_blueprint_index.rb, templates/rspec_api_documentation/api_blueprint_index.mustache
This will include the `default` and `enum` metadata when rendering parameters or attributes.
The following parameter declaration:
```
parameter :status, 'Status', type: :string, default: 'completed', enum: %w[pending complete]
```
Would be rendered as:
```
+ Parameters
+ status (optional, string) - Status
+ Default: `complete`
+ Members
+ `pending`
+ `complete`
```
I've also added the ability to add raw API Blueprint annotations for object attributes, which is useful when describing JSONAPI payloads:
```
attribute :data, type: :object, required: true, annotation: <<~MARKDOWN
+ attributes (required, object)
+ name (required, string)
MARKDOWN
```
This will be rendered to:
```
+ Attributes (object)
+ data (required, object) - 
+ attributes (required, object)
+ name (required, string)
```
=> Add parameter/attribute defaults, enums and annotations for API Blueprint

features/open_api.feature, lib/rspec_api_documentation/writers/open_api_writer.rb
Issue #429 
When multiple required fields were set, only one of them would show on the Open Api schema.
The `required` list would only be populated by the first required value.
This PR changes it so that multiple required values are able to be set on the schema
before:
```ruby
fields.each do |field|
#...
current[:required] ||= [] << field[:name] if field[:required]
end
```
after:
```ruby
fields.each do |field|
#... 
if field[:required]
current[:required] ||= []
current[:required] << field[:name]
end
end
```
=> Fix Open Api: issue with multiple required fields

README.md
When we use `config.disable_dsl_status!` than we can not `expect(status).to eq 200` but we can `expect(status_code).to_eq 200`
#329
=> Add comment about response_status

README.md
I know we all mentally substitute `.should` with `expect()` already, but why keep the mental burden? :wink:
=> Get rid of deprecated .should syntax in readme

README.md
This adds a warning in the readme around configuring docs output path since the directory will be cleared during document generation.
See #441 for context
cc @oestrich @juanmanuelramallo
=> add warning for `config.docs_dir`

README.md, lib/rspec_api_documentation/client_base.rb, lib/rspec_api_documentation/configuration.rb
Following this issue on Rack's repository: [Fix incorrect MockResponse#body String encoding](https://github.com/rack/rack/pull/1486), it looks like we can expect, from now on, that Rack's `response_body` encoding will be `Encoding::ASCII_8BIT`:
> I think the response body should probably always be ASCII-8BIT. Rack can't really know anything about the encoding of the bytes that users want to send. At the end of the day, it's just bytes written to the socket, and I don't think Rack should have any opinion about the encoding the user sends.
Therefore, `rspec_api_documentation` cannot rely on `response_body.encoding` to determine whether the response is binary data or not. This line becomes incorrect:
https://github.com/zipmark/rspec_api_documentation/blob/81e5c563ce6787f143cf775c64e2bd08c35d3 …
=> Allow response_body_formatter config to format "binary" responses

rspec_api_documentation.gemspec, spec/http_test_client_spec.rb
This change is part of preliminary efforts at attempting to refresh
the Continuous Integration setup, by supporting recent Ruby versions and
updating dependencies.
To be honest, I don't know what benefits the Thin server brings to the table.
I tried digging in the code, but the commit that introduced it does not
tell me much: cdeea8b.
What I know however is that I have troubles running the specs locally,
getting a timeout on this line:
https://github.com/zipmark/rspec_api_documentation/blob/560c3bdc7bd5581e7c223334390221ecfc910be8/spec/http_test_client_spec.rb#L16
However, letting Capybara handle its server details, as shown in this PR,
does not seem to have any negative impact (spec is still green, and fairly fast).
=> Remove dev dependency to Thin

.travis.yml
> ⚠️ `root`: deprecated key `sudo` (The key \`sudo\` has no effect anymore.)
=> Remove deprecated key in .travis.yml

README.md, features/readme.md
> ### Why is Gemnasium.com closed?
> Gemnasium was acquired by GitLab in January 2018. Since May 15, 2018, the services provided by Gemnasium are no longer available.
[Source.](https://docs.gitlab.com/ee/user/project/import/gemnasium.html#why-is-gemnasiumcom-closed)
=> Remove Gemnasium links

.travis.yml, lib/rspec_api_documentation/writers/append_json_writer.rb, lib/rspec_api_documentation/writers/writer.rb, spec/api_documentation_spec.rb, spec/writers/html_writer_spec.rb, spec/writers/json_iodocs_writer_spec.rb, spec/writers/json_writer_spec.rb, spec/writers/markdown_writer_spec.rb, spec/writers/slate_writer_spec.rb, spec/writers/textile_writer_spec.rb
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
Addresses https://github.com/zipmark/rspec_api_documentation/issues/505
=> Add Support for Ruby 3.2
